### ISSUE TITLE
AIX support

### ISSUE THREAD

**Issue by zoofood** [ActiveState/appdirs#98]
There is a fair amount of Python development on that platform that it is worth adding. Lower priority than other items in the queue, but want to make sure its here.

**Comment by Kriskras99** [comment]
Currently AIX is handled as linux, is there any documentation which specifies different path conventions than XDG/linux?

**Comment by noloader** [comment]
@Kriskras99,

The [GCC Compile Farm](https://gcc.gnu.org/wiki/CompileFarm) has two AIX machines. The first is AIX 7.1 on a Power7, and it is GCC111. The second is AIX 7.2 on a Power8, and it is GCC119. The boxes are unique because they are AIX, powerpc and big-endian.

If you have an account on the farm, you SSH into a box like so:

    ssh gcc111.fsffrance.org

The compile farm is open to anyone who works on free software. You can sign up for an account at [The GCC Compile Farm project](https://cfarm.tetaneutral.net/). Find the link called *Request an Account*.

**Comment by Kriskras99** [comment]
@noloader Thanks for the tip! I just requested an account.

**Comment by zoofood** [comment]
Unnecessary. Closing.
